name:                Scott Zeid
copyright-start:     2007

author:
 name:               Scott Zeid
 meta:               Scott Zeid // scottywz
 url:                http://s.zeid.me/

url:                 
full-url:            //s.zeid.me
default-scheme:      https    # only necessary with protocol-relative (full-)url
ganalytics:          UA-382238-6    # Optional; uncomment to enable

freecomment:    # Free/libre comment system <http://code.s.zeid.me/freecomment>
 enabled:            True    # Uncomment to enable
 highlight:     # Comments with these Gravatar ID(s) will be highlighted
  - e318793d5d8a9c12094908f3a58aaf3d

internet-defense-league:    # Internet Defense League campaigns
 # Note:  any variable set here will be passed to the `window._idl` object.
 enabled:            True    # Uncomment to enable
 is_test:            #True    # Uncomment to test a campaign
 # Optional settings; blank values mean to use the defaults:
 campaign:           # The campaign to show (default: show all campaigns)
 variant:            modal    # The variant to use (e.g. banner, modal; default: banner)
 url:                # URL of custom message

portal:         # Optional integration with <http://code.s.zeid.me/portal>
 url:                //s.zeid.me/more/    # Uncomment to enable
 highlight:          s.zeid.me
 theme:              new
 max-icons:          16    # Controls the width of the portal's iframe (n*24px)
