#!/usr/bin/env bash

# This file is executed after the site is generated, but before it is
# deployed (moved from ._build/ to _site/).  If you need anything to
# be done at that time, put it here.  You can also use a different
# language by changing the shebang line above.
# 
# This script is given two command-line arguments:  the first is the
# temporary directory in which the site was generated (`._build` by
# default), and the second is the directory in which the site will
# be deployed (`_site` by default).

BUILD_DIR=$1
SITE_DIR=$2

rm -rf $BUILD_DIR/more #$BUILD_DIR/source
ln -s ../_/more $BUILD_DIR/more
#ln -s .. $BUILD_DIR/source
rm -f $SITE_DIR/more
if [ -h "$SITE_DIR/source" ]; then
 rm -f "$SITE_DIR/source"
fi
